// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using shared_classes.Data;

namespace webapi.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20191022161623_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("shared_classes.Models.BlogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AuthorId");

                    b.Property<DateTime>("DateStarted");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("shared_classes.Models.CommentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AuthorId");

                    b.Property<int>("BlogId");

                    b.Property<int>("PostId");

                    b.Property<int?>("PostModelId");

                    b.Property<string>("Text");

                    b.Property<DateTime>("TimePosted");

                    b.HasKey("Id");

                    b.HasIndex("PostModelId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("shared_classes.Models.PostModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AuthorId");

                    b.Property<int>("BlogId");

                    b.Property<int?>("BlogModelId");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.Property<DateTime>("TimePosted");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("BlogModelId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("shared_classes.Models.CommentModel", b =>
                {
                    b.HasOne("shared_classes.Models.PostModel")
                        .WithMany("Comments")
                        .HasForeignKey("PostModelId");
                });

            modelBuilder.Entity("shared_classes.Models.PostModel", b =>
                {
                    b.HasOne("shared_classes.Models.BlogModel")
                        .WithMany("Posts")
                        .HasForeignKey("BlogModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
